name: core_network_model
description: This package provides network model classes.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.4

dependencies:
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0

dev_dependencies:
  build_runner: 2.4.13
  freezed: 2.5.7
  json_serializable: 6.9.0
  yumemi_lints: 3.1.0
