name: core_common
description: This package provides convenience functions and other functions commonly used in packages.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.4

dependencies:
  anyhow: 1.3.2
  collection: 1.18.0
  rust_core: 1.3.7
  simple_logger: 1.10.0

dev_dependencies:
  test: 1.25.9
  yumemi_lints: 3.1.0
