name: core_database
description: This package provides local database operations.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.5.4

dependencies:
  core_common:
    path: ../common
  core_model:
    path: ../model
  isar:
    hosted: https://pub.isar-community.dev/
    version: 4.0.3
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.13
  core_testing:
    path: ../testing
  riverpod_generator: 2.6.3
  test: 1.25.9
  yumemi_lints: 3.1.0
