name: app_backend
description: An new Dart Frog application
version: 0.1.0
publish_to: none

environment:
  sdk: 3.5.4

dependencies:
  built_value: 8.9.2
  core_network_model:
    path: ../../core/network_model
  dart_frog: 1.1.0
  ferry: 0.16.0+1
  gql_code_builder: 0.13.0
  gql_error_link: 1.0.0+1
  gql_exec: 1.0.0+1
  gql_http_link: 1.1.0
  gql_link: 1.0.0+1
  gql_transform_link: 1.0.0
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1

dev_dependencies:
  build_runner: 2.4.13
  ferry_generator: 0.12.0
  mocktail: 1.0.4
  riverpod_generator: 2.6.3
  test: 1.25.9
  yumemi_lints: 3.1.0

dependency_overrides:
  freezed_annotation: 2.4.3
