name: app_catalog
description: "Catalog app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.5.4
  flutter: 3.24.5

dependencies:
  core_common:
    path: ../../core/common
  core_designsystem:
    path: ../../core/designsystem
  core_domain:
    path: ../../core/domain
  core_model:
    path: ../../core/model
  core_ui:
    path: ../../core/ui
  feature_contact:
    path: ../../feature/contact
  feature_home:
    path: ../../feature/home
  feature_miscellaneous:
    path: ../../feature/miscellaneous
  flutter:
    sdk: flutter
  flutter_riverpod: 2.6.1
  widgetbook: 3.11.0
  widgetbook_annotation: 3.3.0

dev_dependencies:
  build_runner: 2.4.13
  widgetbook_generator: 3.10.0
  yumemi_lints: 3.1.0

flutter:
  uses-material-design: true
